[[update]]
url = "https://raw.githubusercontent.com/joeisawesome35/plexiglass-tweaked-updater/main/1.0.toml"
version = "1.0.0"

[[update]]
url = "https://raw.githubusercontent.com/joeisawesome35/plexiglass-tweaked-updater/main/1.1.toml"
version = "1.1.0"

[[update]]
url = "https://raw.githubusercontent.com/joeisawesome35/plexiglass-tweaked-updater/main/1.2.toml"
version = "1.2.0"

[[update]]
url = "https://raw.githubusercontent.com/joeisawesome35/plexiglass-tweaked-updater/main/1.3.toml"
version = "1.3.0"

[[update]]
url = "https://raw.githubusercontent.com/joeisawesome35/plexiglass-tweaked-updater/main/1.4.toml"
version = "1.4.0"

[[update]]
url = "https://raw.githubusercontent.com/joeisawesome35/plexiglass-tweaked-updater/main/1.5.toml"
version = "1.5.0"
